name: Naukri API Automation

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Naukri automation script
        run: python naukri_automation.py
